### ISSUE TITLE
transliterate_bilstm doesn't work

### ISSUE THREAD

**Issue by leedrake5** [gaigutherz/Akkademia#4]
I'm not sure transliterate_bilstm is functional (or that the installation description is complete). Tried on both Mac and linux. Even though allennlp==0.8.5. python version is 3.7.6, and torch is 1.1.0 (version selected by pip for specified allennlp, though result is same for 1.3.1). 

```
>>> print(akk.transliterate_bilstm("𒃻𒅘𒁀𒄿𒈬𒊒𒅖𒁲𒈠𒀀𒋾"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/akkadian/transliterate.py", line 34, in transliterate_bilstm
    model, predictor, sign_to_id, id_to_tran, test_texts = load_object_from_file(bilstm_path)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/akkadian/data.py", line 184, in load_object_from_file
    object = pickle.load(input)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/akkadian/bilstm.py", line 4, in <module>
    from allennlp.data import Instance
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 50, in ArrayField
    @overrides
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 83, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 172, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 191, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/signature.py", line 103, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/signature.py", line 304, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

```

**Comment by leedrake5** [comment]
Digging deeper, this seems to be an almost universal problem. On a linux system with allennlp=0.8.5 and torch 1.1 or 1.0, the same error comes up. In fact, merely importing a script triggers it:

```
>>> import akkadian.train

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/GitHub/Akkademia/akkadian/train.py", line 1, in <module>
    from allennlp.predictors import SentenceTaggerPredictor
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/predictors/__init__.py", line 9, in <module>
    from allennlp.predictors.predictor import Predictor
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 11, in <module>
    from allennlp.data import DatasetReader, Instance
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 10, in <module>
    from allennlp.data.fields import Field, TextField, SequenceLabelField
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 50, in ArrayField
    @overrides
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 83, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 172, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/overrides.py", line 191, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/signature.py", line 103, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/home/<user>/anaconda3/envs/assyria/lib/python3.7/site-packages/overrides/signature.py", line 304, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.
```

I'm sure there is a configuration that will work, but not sure the documentation leads there.

**Comment by leedrake5** [comment]
Fixed it! The issue is with the allennlp dependency overrides, [more about it here](https://github.com/allenai/allennlp/issues/5217#issuecomment-846049422). The following must be added to the installation instructions:

```
pip install overrides==3.1.0
pip install allennlp==0.8.5
```

**Comment by gaigutherz** [comment]
Thank you @leedrake5 for finding the issue with the instructions in the README file and suggesting a solution.

**Comment by gaigutherz** [comment]
Solved in https://github.com/gaigutherz/Akkademia/pull/5
